# Generated by Django 4.2.30 on 2026-06-08 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatetenant',
            name='user',
            field=models.OneToOneField(blank=True, help_text='The login account for this candidate. Set when creating the tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidate_tenant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidatetenant',
            name='subscription_plan',
            field=models.CharField(choices=[('STARTER', 'Starter'), ('PROFESSIONAL', 'Professional'), ('FULL_PACKAGE', 'Full Package')], default='STARTER', max_length=24),
        ),
        migrations.AlterField(
            model_name='planaimodel',
            name='plan',
            field=models.CharField(choices=[('STARTER', 'Starter'), ('PROFESSIONAL', 'Professional'), ('FULL_PACKAGE', 'Full Package')], max_length=24),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('STARTER', 'Starter'), ('PROFESSIONAL', 'Professional'), ('FULL_PACKAGE', 'Full Package')], max_length=24),
        ),
    ]
